version: '3'

services:
     docker-registry:
                image:  infracloudio/csvserver:latest
                container_name: infracloudio-csvserver
                ports:
                        - "9393:9300"
                restart: always
                volumes:
                        - /home/roopesh/solution/solution/inputFile:/csvserver/inputdata:ro

                environment:
                          CSVSERVER_BORDER: Orange

     docker-registry:
                image:  prom/prometheus:v2.22.0
                container_name: prometheus
                ports:
                        - "9090:9090"
                        
                restart: always
                volumes:
                        - /home/roopesh/solution/solution/inputFile:/csvserver/inputdata:ro
                        - /home/roopesh/solution/solution/prometheus.yaml:/etc/prometheus/prometheus.yml:rw
